In [1]:
!pip install ipython --upgrade
!pip install jedi
!pip3 install jupyter-tabnine
!jupyter nbextension install --py jupyter_tabnine
!jupyter nbextension enable --py jupyter_tabnine
!jupyter serverextension enable --py jupyter_tabnine

Requirement already up-to-date: ipython in c:\users\yavuz\anaconda3\lib\site-packages (7.28.0)


Installing C:\Users\yavuz\anaconda3\lib\site-packages\jupyter_tabnine\static -> jupyter_tabnine
Making directory: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\
Copying: C:\Users\yavuz\anaconda3\lib\site-packages\jupyter_tabnine\static\main.css -> C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\main.css
Copying: C:\Users\yavuz\anaconda3\lib\site-packages\jupyter_tabnine\static\main.js -> C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\main.js
Copying: C:\Users\yavuz\anaconda3\lib\site-packages\jupyter_tabnine\static\README.md -> C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\README.md
Copying: C:\Users\yavuz\anaconda3\lib\site-packages\jupyter_tabnine\static\tabnine.yaml -> C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\tabnine.yaml
- Validating: ok

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable jupyter_tabnine --py
    
Enabling notebook extension jupyter_tabnine/main...

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data=[1,3,5,7,9]
data

[1, 3, 5, 7, 9]

In [6]:
pd.DataFrame(data,columns=["col1"]) #colunm ve index var

col1
0     1
1     3
2     5
3     7
4     9

In [7]:
pd.Series(data)

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [9]:
data2=np.arange(1,24,2).reshape(3,4)
data2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [10]:
pd.DataFrame(data2,columns=["col1","col2","col3","col4"]) #indeks ve column isimleri kazandı

col1  col2  col3  col4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [13]:
df=pd.DataFrame(data2,columns=["col1","col2","col3","col4"],index=["a","b","c"]) #yapı dataframe label verebilriz

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.size

12

In [16]:
df.shape

(3, 4)

In [17]:
df.ndim

2

In [18]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [19]:
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [20]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [21]:
df.keys()

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [22]:
len(df)

3

In [23]:
df.col1

a     1
b     9
c    17
Name: col1, dtype: int32

In [24]:
df["col1"]

a     1
b     9
c    17
Name: col1, dtype: int32

In [25]:
s1 = np.random.randint(2,10, size = 40)
s2 = np.random.randint(30,100, size = 40)
s3 = np.random.randint(100,150, size = 40)
s1

array([3, 3, 3, 2, 9, 3, 6, 8, 7, 4, 2, 7, 4, 7, 5, 2, 9, 8, 5, 9, 5, 8,
       3, 3, 9, 4, 2, 2, 9, 8, 7, 4, 5, 6, 4, 7, 7, 2, 4, 5])

In [26]:
my_dicc={"var1":s1,"var2":s2,"var3":s3}
my_dicc

{'var1': array([3, 3, 3, 2, 9, 3, 6, 8, 7, 4, 2, 7, 4, 7, 5, 2, 9, 8, 5, 9, 5, 8,
        3, 3, 9, 4, 2, 2, 9, 8, 7, 4, 5, 6, 4, 7, 7, 2, 4, 5]),
 'var2': array([86, 97, 79, 40, 61, 57, 75, 75, 77, 64, 82, 50, 54, 47, 60, 31, 39,
        95, 74, 47, 95, 69, 35, 93, 57, 57, 44, 40, 35, 94, 60, 56, 53, 66,
        34, 73, 64, 41, 75, 90]),
 'var3': array([141, 128, 133, 126, 130, 109, 127, 109, 130, 146, 132, 112, 107,
        131, 106, 119, 115, 109, 148, 118, 135, 117, 102, 138, 109, 122,
        139, 128, 144, 123, 140, 120, 134, 145, 130, 112, 147, 112, 102,
        141])}

In [28]:
dfdicc=pd.DataFrame(my_dicc) # 40 adet elemanı attı
dfdicc

var1  var2  var3
0      3    86   141
1      3    97   128
2      3    79   133
3      2    40   126
4      9    61   130
5      3    57   109
6      6    75   127
7      8    75   109
8      7    77   130
9      4    64   146
10     2    82   132
11     7    50   112
12     4    54   107
13     7    47   131
14     5    60   106
15     2    31   119
16     9    39   115
17     8    95   109
18     5    74   148
19     9    47   118
20     5    95   135
21     8    69   117
22     3    35   102
23     3    93   138
24     9    57   109
25     4    57   122
26     2    44   139
27     2    40   128
28     9    35   144
29     8    94   123
30     7    60   140
31     4    56   120
32     5    53   134
33     6    66   145
34     4    34   130
35     7    73   112
36     7    64   147
37     2    41   112
38     4    75   102
39     5    90   141

In [29]:
dfdicc[3:5]

var1  var2  var3
3     2    40   126
4     9    61   130

In [33]:
dfdicc[1:2]

var1  var2  var3
1     3    97   128

In [34]:
df_dicc2=dfdicc[1:3]
df_dicc2.index=["a","b"]
df_dicc2

var1  var2  var3
a     3    97   128
b     3    79   133

In [35]:
df_dicc2.columns=["col1","col2","col3"] #columlarımada müdahale ettik
df_dicc2

col1  col2  col3
a     3    97   128
b     3    79   133

In [36]:
df_dicc2["col3"]

a    128
b    133
Name: col3, dtype: int32

In [38]:
pd.DataFrame(df_dicc2.values,columns=["la","le","li"],index=["t","r"])
df_dicc2

col1  col2  col3
a     3    97   128
b     3    79   133

In [43]:
np.random.seed(101)
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [45]:
np.random.seed(101)
df3=pd.DataFrame(np.random.randn(5,4),
                  index="A B C D E".split(),
                  columns="W X Y Z".split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df3["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [47]:
df3[["W"]]  #şimdi dataframe

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [48]:
df3[["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [49]:
df3.loc[:,"W":"Y"] #location

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077
C -2.018168  0.740122  0.528813
D  0.188695 -0.758872 -0.933237
E  0.190794  1.978757  2.605967

In [51]:
df3["X"] * df3["Y"]**2

A     0.517838
B    -0.229665
C     0.206970
D    -0.660926
E    13.437871
dtype: float64

In [56]:
df3["result"]=df3["W"]*df3["X"] + df3["Y"] #tüm herşeyi yapabiliriz
df3

W         X         Y         Z    result
A  2.706850  0.628133  0.907969  0.503826  2.608230
B  0.651118 -0.319318 -0.848077  0.605965 -1.055991
C -2.018168  0.740122  0.528813 -0.589001 -0.964877
D  0.188695 -0.758872 -0.933237  0.955057 -1.076433
E  0.190794  1.978757  2.605967  0.683509  2.983503

In [59]:
df3.drop("result",axis=1) # resultu düşürmek istersek kalıcı değişiklik yapmaz


W         X         Y         Z    result
A  2.706850  0.628133  0.907969  0.503826  2.608230
B  0.651118 -0.319318 -0.848077  0.605965 -1.055991
C -2.018168  0.740122  0.528813 -0.589001 -0.964877
D  0.188695 -0.758872 -0.933237  0.955057 -1.076433
E  0.190794  1.978757  2.605967  0.683509  2.983503

In [61]:
df3.drop(["Y","result"],axis=1)

W         X         Z
A  2.706850  0.628133  0.503826
B  0.651118 -0.319318  0.605965
C -2.018168  0.740122 -0.589001
D  0.188695 -0.758872  0.955057
E  0.190794  1.978757  0.683509

In [62]:
df3.drop(["C","D"],axis=0) #satır ve sütun düşebiliriz

W         X         Y         Z    result
A  2.706850  0.628133  0.907969  0.503826  2.608230
B  0.651118 -0.319318 -0.848077  0.605965 -1.055991
E  0.190794  1.978757  2.605967  0.683509  2.983503

In [63]:
m=np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4']) #loc iloc kavramları
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [64]:
df4.loc[2] #burayı seri olarak dönderdi

var1    13
var2    18
var3    12
var4    16
Name: 2, dtype: int32

In [65]:
df4.loc[2:6]  #burayı dataframe olarak dönderdi

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23

In [69]:
df4.index="a b c d e f g h".split()
df4


var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [70]:
df4.loc["c"]

var1    13
var2    18
var3    12
var4    16
Name: c, dtype: int32

In [71]:
df4.loc["c":"g"] #c yi ve g yide alır

var1  var2  var3  var4
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23

In [72]:
df4.loc["c":"f","var1":"var3"]          #locationun yanına sütunvermek istiyorsak

var1  var2  var3
c    13    18    12
d    34    30    25
e    20    36    31
f    21    28     9

In [74]:
df4.loc[['c','f'],['var1','var3']]

var1  var3
c    13    12
f    21     9

In [75]:
df4.iloc[1:4,2:4]

var3  var4
b    16     1
c    12    16
d    25    37

In [76]:
df4.iloc[1:4,2:3]

var3
b    16
c    12
d    25

In [77]:
df3

W         X         Y         Z    result
A  2.706850  0.628133  0.907969  0.503826  2.608230
B  0.651118 -0.319318 -0.848077  0.605965 -1.055991
C -2.018168  0.740122  0.528813 -0.589001 -0.964877
D  0.188695 -0.758872 -0.933237  0.955057 -1.076433
E  0.190794  1.978757  2.605967  0.683509  2.983503

In [78]:
df3.iloc[:,2:4] #loc ve iloc için aynı mantık kullanılabiliyor

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057
E  2.605967  0.683509

In [79]:
####CONDİTİONAL SELECTİON

In [80]:
df3

W         X         Y         Z    result
A  2.706850  0.628133  0.907969  0.503826  2.608230
B  0.651118 -0.319318 -0.848077  0.605965 -1.055991
C -2.018168  0.740122  0.528813 -0.589001 -0.964877
D  0.188695 -0.758872 -0.933237  0.955057 -1.076433
E  0.190794  1.978757  2.605967  0.683509  2.983503

In [81]:
df3[df3["X"]>0]

W         X         Y         Z    result
A  2.706850  0.628133  0.907969  0.503826  2.608230
C -2.018168  0.740122  0.528813 -0.589001 -0.964877
E  0.190794  1.978757  2.605967  0.683509  2.983503

In [82]:
df3[(df3["X"]>0) & (df3["Z"]>0)]

W         X         Y         Z    result
A  2.706850  0.628133  0.907969  0.503826  2.608230
E  0.190794  1.978757  2.605967  0.683509  2.983503

(2, 0)
