In [2]:
import numpy as np
import pandas as pd
liste=[1,2,3,5,4]
liste.sort()
liste

[1, 2, 3, 4, 5]

In [3]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b[1,1]=77
b

array([[ 1,  2,  3],
       [ 4, 77,  6]])

In [5]:
b[:,1]=50   #broadcasting oluyor istenilen yapılabilir
b

array([[ 1, 50,  3],
       [ 4, 50,  6]])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arange(5,60,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [19]:
np.linspace(0,40,21)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40.])

In [20]:
np.random.rand(3,3) #uniform dağılım değerler 0 ve 1 arasında

array([[0.90338595, 0.24290836, 0.19961768],
       [0.25775382, 0.42780837, 0.1128617 ],
       [0.18658715, 0.81479054, 0.73820299]])

In [21]:
np.random.randn(3,3)               #ortalaması 0dır varyansı 1 olacak şekilde değerler olur çan eğrisini tutturabilmek için

array([[ 0.40211542,  1.24159581, -0.40643392],
       [-0.25740479, -0.05325357,  1.22493791],
       [ 1.03025096, -0.25342488, -0.21289057]])

In [22]:
np.random.randint(0,5,size=(3,3)) #3 e 3 lük bir matris

array([[2, 3, 0],
       [2, 3, 3],
       [4, 4, 2]])

In [31]:
z=np.random.randint(0,10,size=(4,4))
z.shape
z.reshape(2,8)


array([[2, 9, 0, 7, 4, 6, 1, 1],
       [0, 9, 1, 4, 6, 8, 2, 7]])

In [33]:
z=z.ravel() #tek satırda listeye çevirir tek boyutlu bir array oluşturur ravel
z

array([2, 9, 0, 7, 4, 6, 1, 1, 0, 9, 1, 4, 6, 8, 2, 7])

In [34]:
z.max()

9

In [35]:
z.min()

0

In [37]:
z.argmax() # maximum olan sayının indexini veriyor

1

In [38]:
z.argmin()# minimum olan sayının indeksini verir

2

In [39]:
my_array=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(5,2)
my_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [40]:
my_array1=np.array([11,12,13,4,5,6,7,8,9,10]).reshape(5,2)
my_array1

array([[11, 12],
       [13,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
np_caon=np.concatenate([my_array,my_array1],axis=1)
np_caon

array([[ 1,  2, 11, 12],
       [ 3,  4, 13,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [43]:
np_caon[2,[1,3]]

array([6, 6])

In [44]:
np_caon[[1,3],2]

array([13,  7])

In [47]:
np_caon[:,[0,3]]

array([[ 1, 12],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [50]:
import pandas as pd
my_list = [1,2,3,4,5,6,7,8]
a=np.array(my_list)
pd.Series(my_list)
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [53]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}
pd.Series(my_list,index=labels)


X     5
y    10
z    15
h    20
dtype: int64

In [58]:
ser = pd.Series([5,100,15,20,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])
ser #pandasta seriler var numpyda arrayler var
ser.sort_values()
ser.sort_index()

France      15
Germany    100
Greece      30
Turkey      25
UK          20
USA          5
dtype: int64

In [59]:
"Turkey" in ser #keyler üzerinden  üzerinden

True

In [60]:
ser.isin([100]) #valuelar üzerinden isin

USA        False
Germany     True
France     False
UK         False
Turkey     False
Greece     False
dtype: bool

In [62]:
ser.items

<bound method Series.items of USA          5
Germany    100
France      15
UK          20
Turkey      25
Greece      30
dtype: int64>

In [63]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [65]:
for key,value in ser.items():
    print(key,value)

USA 5
Germany 100
France 15
UK 20
Turkey 25
Greece 30


In [ ]:
#Data frameler

In [67]:
m=np.arange(1,30,2).reshape(3,5)
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [68]:
df=pd.DataFrame(m,columns=["col1","col2","col3","col4","col5"])
df

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19
2    21    23    25    27    29

In [70]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5'], dtype='object')